input.onButtonPressed(Button.A, function () {
    led.stopAnimation()
})
basic.forever(function () {
    music.playMelody("E D G F B A C5 B ", 120)
    basic.showString("Hello!")
    basic.showIcon(IconNames.Happy)
    music.playMelody("A F E F D G E F ", 120)
    basic.showString(" You are gonna die!")
    basic.showIcon(IconNames.Happy)
    music.playMelody("E B C5 A B G A F ", 120)
    basic.clearScreen()
    basic.showString("           ")
    for (let index = 0; index < randint(0, 10); index++) {
        music.playMelody("C D E F G A B C5 ", 120)
        basic.showString(" Huh?")
        basic.showIcon(IconNames.Sad)
        music.playMelody("G B A G C5 B A B ", 120)
        basic.showString(" bruh")
        game.addScore(1)
    }
    music.playMelody("C5 B A G F E D C ", 120)
    basic.showIcon(IconNames.Happy)
    basic.showString(" HA! YOU COUDN'T RUN AWAY FOREVER!")
    music.playMelody("C5 A B G A F G E ", 120)
    basic.showIcon(IconNames.Ghost)
    music.playMelody("D D D D D D D D ", 307)
    basic.showIcon(IconNames.Skull)
    basic.showString(" Goodbye!")
    music.playMelody("C5 G B A F A C5 B ", 120)
    game.gameOver()
})
